spring:
  data:
    redis:
      database: 0
      host: 192.168.84.30
      port: 6379
      password: redis_aYWNrS
      timeout: 15000


logging:
  level:
    root: INFO
    com.shengong: DEBUG
    dev.langchain4j: DEBUG
